const myPetsArray = [
	{
		id: "1",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "2",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "3",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "4",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "5",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "6",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "7",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
	{
		id: "8",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "some_id",
	},
];

const savedPetsArray = [
	{
		id: "9",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "10",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "11",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "12",
		image_url:
			"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?cs=srgb&dl=pexels-chevanon-photography-1108099.jpg&fm=jpg",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "13",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "14",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "15",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
	{
		id: "16",
		image_url: "https://bit.ly/2Z4KKcF",
		image_alt: "Rear view of modern home with pool",
		type: "Dog",
		name: "Poppy",
		adoption_status: "Adopted",
		height: 50,
		weight: 50,
		color: "brown",
		bio: "large bio with alot of words and things inside of it do i see or do you understand",
		hypoallergenic: true,
		dietary_restrictions: "none",
		breed: "Poodle",
		ownerId: "1",
	},
];

const allPetsArray = [...myPetsArray, ...savedPetsArray];
export { myPetsArray, savedPetsArray, allPetsArray };
